sudo: required

services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_40e932f81a14_key -iv $encrypted_40e932f81a14_iv -in .travis/login.json.enc -out export/login.json -d
  - docker pull dhimmel/thinklytics

script:
- docker run --volume `pwd`:/thinklytics --workdir /thinklytics dhimmel/thinklytics sh run.sh
