sudo: required

language: generic

services:
  - docker

git:
  depth: 1

before_install:
  - openssl aes-256-cbc -K $encrypted_40e932f81a14_key -iv $encrypted_40e932f81a14_iv
    -in .travis/login.json.enc -out export/login.json -d
  - openssl aes-256-cbc -K $encrypted_a6d31e15473c_key -iv $encrypted_a6d31e15473c_iv
    -in .travis/deploy_key.enc -out .travis/deploy_key -d
  - docker pull dhimmel/thinklytics

script:
  - docker run --volume `pwd`:/thinklytics --workdir /thinklytics dhimmel/thinklytics
    sh run.sh

after_success:
  - sh .travis/push.sh
